### PR TITLE
MSVC14/windows10 SDK support, 64bit binary

### PR DESCRIPTION
**Pull request by XenHat**
Note: it's probably better to use the included solution, nmake-based builds are still generating broken bison files on windows. I included fixed ones in case.

### CODE REVIEW

**Comment by Makopo** [comment]
Thank you. I keep lslint be able to use on Windows XP. Will it still be able to work after merging?

**Comment by XenHat** [comment]
Hm. I cannot test myself but I can modify the solution to generate binaries compatible with windowsXP, yes. the nmake process should still work, but I will add a fallback.

**Comment by Makopo** [comment]
Thanks!

**Comment by Makopo** [comment]
Thank you! I'll look at it. I confirmed I can compile it on Windows 10 native console. I found I can even compile on Windows 7 SDK shell. I'm still not yet try it on Windows XP, so I'll do later.

**Comment by buildersbrewery** [comment]
@XenHat Not sure how much time you have on your hand. Maybe you could resolve some of [the issues of `pclewis/lslint`](https://github.com/pclewis/lslint/issues). You could close the issues by something like `fixes pclewis/lslint#000`, if @pclewis was willing to merge the changes from here into his repo.

**Comment by XenHat** [comment]
@buildersbrewery But I can't really change a repo's description with a commit, can I?

**Comment by buildersbrewery** [comment]
@XenHat Do that by logging in on Github and visiting the repo page. Then click the <kbd>Edit</kbd> button at the top right.

**Comment by XenHat** [comment]
Well I edited my own fork, it does not leave a commit and I do not have access on pclewis' repo, so I'm not quite sure what to do about pclewis/lslint/#17

**Comment by buildersbrewery** [comment]
He'll have to do it on his own.

**Comment by XenHat** [comment]
Right, that's what I thought. Will go through the issues, see if I can help.

**Comment by XenHat** [comment]
I need a break but I may compact the commits later. I don't like how many there are.

**Comment by pclewis** [comment]
@XenHat @Makopo @buildersbrewery If someone's interested in taking over as maintainer of lslint I'm happy to give someone push rights on my repo or change the link on w-hat.com to somebody's else repo.

**Comment by XenHat** [comment]
lslint itself is written in a language I do not know, or at least
recognize. Is this C? The flex/bison parts are not part of what I know, so
it is unlikely that I am the right person to become the maintainer for the
current lslint implementation.

**Comment by buildersbrewery** [comment]
@pclewis I'd like to help with lslint itself, but I'm neither a professional developer, nor pretending to be. Though I probably know more LSL than I should. Anyhow, I'd take care of the issue management, docs and updating the lsl test scripts of the repo if that helps.

@XenHat It's `C++` to me.

**Comment by XenHat** [comment]
Yeah, I know a bit of C++, enough to get by doing my daily hobbies, but I'm
not a professional developer either. I mainly focus on the SL client
itself. I started poking at lslint because it's a tool I use regularly and
saw no reason to not add 64bit support. I'll be happy to provide help
should it be needed.

**Comment by Makopo** [comment]
Since I confirmed that the output can still work win Windows XP just now, I merged this request. I could choose squashing your commit during merge. Each of your commit messages went inside the description of a commit. Thank you!

**Comment by Makopo** [comment]
@pclewis I know mine is only the maintained fork of lslint. Since I initially created this fork for use in [my lsl plugin](/Makopo/sublime-text-lsl), and added some functions in need of it. I appreciate if you would have a link to my fork in w-hat.com.

**Comment by XenHat** [comment]
@Makopo No problem. Glad to help.

**Pull request merged**
